# Generated by Django 3.2.3 on 2021-09-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coproperties', '0006_auto_20210906_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargesSpecific',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time object created', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Save method update this field', verbose_name='modified_at')),
                ('status', models.CharField(choices=[('FINALIZED', 'Finalized'), ('OPEN', 'Open'), ('SUSPEND', 'Suspend')], default='OPEN', max_length=15)),
                ('reason', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('money', models.DecimalField(decimal_places=2, max_digits=15)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_specific', to='coproperties.property')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ChargesGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time object created', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Save method update this field', verbose_name='modified_at')),
                ('status', models.BooleanField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('coproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges_general', to='coproperties.coproperty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
