# Generated by Django 3.2.3 on 2021-09-06 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coproperties', '0006_auto_20210906_1137'),
        ('payments', '0002_chargesgeneral_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargesgeneral',
            name='coproperty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charges_general', to='coproperties.coproperty'),
        ),
    ]
