# Generated by Django 3.2.3 on 2021-06-01 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reputation',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sales_done_count',
        ),
        migrations.AddField(
            model_name='profile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date time object created', verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Save method update this field', verbose_name='modified_at'),
        ),
    ]
