# Generated by Django 3.2.3 on 2021-06-01 20:24

from django.db import migrations
from django.contrib.auth.admin import User
from django.contrib.auth.models import Group
from utils.constants import roles

def create_superuser(apps, schema_editor):
    superuser = User()
    superuser.is_active = True
    superuser.is_superuser = True
    superuser.is_staff = True
    superuser.username = 'superadmin'
    superuser.email = 'superadmin@admin.co'
    superuser.set_password('superadmin')
    superuser.save()

def create_groups(apps, schema_editor):
    for role in roles:
        group = Group()
        group.name = role
        group.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210601_1509'),
    ]

    operations = [
        migrations.RunPython(create_superuser),
        migrations.RunPython(create_groups)
    ]
