# Generated by Django 3.2.7 on 2021-09-19 21:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bussiness', '0002_alter_business_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coproperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time object created', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Save method update this field', verbose_name='modified_at')),
                ('name', models.CharField(max_length=100)),
                ('logo_coproperty', models.ImageField(blank=True, null=True, upload_to='images/logo/coproperty', verbose_name='logo_coproperty')),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coproperty', to='bussiness.business')),
                ('user_coproperty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coproperty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time object created', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Save method update this field', verbose_name='modified_at')),
                ('apto', models.CharField(max_length=100)),
                ('block', models.IntegerField(verbose_name='block')),
                ('type_property', models.CharField(choices=[('APTO', 'Apto'), ('PARK', 'Park')], default='APTO', max_length=9)),
                ('emails', models.EmailField(blank=True, max_length=254)),
                ('clustering_coefficient', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('agrouping', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
                ('coproperty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property', to='coproperties.coproperty')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
