# Generated by Django 3.2.3 on 2021-06-01 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bussiness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coproperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time object created', verbose_name='created_at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Save method update this field', verbose_name='modified_at')),
                ('name', models.CharField(max_length=100)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coproperty', to='bussiness.business')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
