# Generated by Django 3.2.3 on 2021-08-26 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('coproperties', '0003_coproperty_logo_coproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='coproperty',
            name='user_coproperty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coproperty', to='auth.user'),
            preserve_default=False,
        ),
    ]
